### ISSUE TITLE
include link to barracks example in readme

### ISSUE THREAD

**Issue by yoshuawuyts** [acdlite/flux-standard-action#13]
I wrote an example of using [fsa with `barracks`](https://github.com/yoshuawuyts/barracks/blob/master/examples/flux-standard-action.js). I'd write a PR, but I'm not sure where to put the link. What is your preferred location to link to the example in the fsa readme? Thanks!

**Comment by JaKXz** [comment]
Closing as stale, sorry this was never addressed. Feel free to open a PR for anything and it will be discussed :)
