### ISSUE TITLE
Question/Clarification re: "Two actions with the same type MUST be strictly equivalent"

### ISSUE THREAD

**Issue by lettertwo** [acdlite/flux-standard-action#14]
As defined in the [readme](https://github.com/acdlite/flux-standard-action/blob/64eac5451643826d3f972381f745404a8bcc59fa/README.md#type), I _think_ a strict reading says that two actions of the same type must be strictly equivalent, i.e.:

``` javascript
firstActionOfTypeA === secondActionOfTypeA
```

But my _interpretation_ is that the intent is to say that the `type` values must be strictly equivalent, not the two actions themselves, i.e.:

``` javascript
firstActionOfTypeA.type === secondActionOfTypeA.type
firstActionOfTypeA !== secondActionOfTypeA
```

If i'm both reading and interpreting correctly, I think the section might need rewording. So my question is, am I doing both of those things correctly? :stuck_out_tongue:

**Comment by xonev** [comment]
+1 This is confusing.

**Comment by cappslock** [comment]
Yeah, I had the exact same thought.

**Comment by tshinnic** [comment]
+1 definitely confusing as it says the action (object) MUST be identical
