### ISSUE TITLE
What is the reason action name is called "type"?

### ISSUE THREAD

**Issue by gajus** [acdlite/flux-standard-action#15]
What is the origin of a convention to call action name (e.g. `ADD_NAME`, `REMOVE_NAME`) a "type" (or "actionType" or "actionId")?

"actionId" is the most accurate of the suggested variations. However, what we are calling a "type" is actually a "name".

It is easy to see that "type" is wrong if you either lookup dictionary definition or try to replace it with either of the direct synonyms (e.g. kind, sort, variety).

**Comment by cesarandreu** [comment]
Probably legacy reasons. Facebook's flux examples use `actionType`.

**Comment by gajus** [comment]
Have a look at https://github.com/gajus/canonical-reducer-composition. It is a broader standard I have been working on. It encompasses actions and reducer definition.
