### ISSUE TITLE
Consider renaming `body` to `payload`?

### ISSUE THREAD

**Issue by jprichardson** [acdlite/flux-standard-action#2]
By request from #redux on reactiflux...

Admittedly this is pedantic, would you consider renaming `body` to `payload`? I thought the term `payload` was used in Facebook's original Flux guides, but I didn't see it. So perhaps other implementations use `payload`? I know that you had commented that Flummox uses `body`. It probably doesn't matter much, but `body` makes me think that I'm dealing with a web response.

**Comment by jprichardson** [comment]
As pointed out by **raydeo** on #redux, `payload` is found all over this page: https://facebook.github.io/flux/docs/dispatcher.html

**Comment by acdlite** [comment]
`payload` on that page refers to the action itself. But I'm cool with renaming with payload. It's clearer that way.
