### ISSUE TITLE
Get state in action creator

### ISSUE THREAD

**Issue by jacobrask** [acdlite/flux-standard-action#20]
With the thunk middleware, you get `getState` as the second argument.

Do you have any suggestion on how I could use the current store state in my promise?
Currently I need this to get auth tokens for my API.

**Comment by dariocravero** [comment]
Hopefully I got you right :). If you need state data you can always return a thunk that dispatches a promise in the payload, e.g.:

```js
import * as users from './api';

export const LOAD = 'my-app/LOAD';
export function load() {
  return function loadThunk(dispatch, getState) {
    dispatch({
      type: LOAD,
      payload: users.load(getState().credentials)
    });
  }
}
```

**Comment by JaKXz** [comment]
Hopefully your question was answered. I think S/O is a better platform for these :)
