### ISSUE TITLE
when to update to babel6 ?

### ISSUE THREAD

**Issue by tantou** [acdlite/flux-standard-action#25]
I use the `redux-actions` && `redux-promise` and `React-Native 0.17` ,but the `RN17` use `babel 6`,and and `redux-actions` && `redux-promise` dependency `flux-standard-action` which use `babel 5`
so ,My Project can not be builded success, so that I have to change the `React Native` to 14
So,Could you update to the `Babel 6 `?

**Comment by hero78119** [comment]
I run into the same issue when use `react-native` 0.17 + `redux-actions` + `redux-promise` when try the 
```
TransformError: MyProject/node_modules/flux-standard-action/lib/index.js: [BABEL] MyProject/node_modules/flux-standard-action/lib/index.js: Unknown option: MyProject/node_modules/flux-standard-action/.babelrc.stage
```

**Comment by ilearnio** [comment]
Same here. I'm getting `isFSA === undefined` when doing
```javascript
import isFSA from 'flux-standard-action'
```
So I had to use `require` instead
