### ISSUE TITLE
Description of type

### ISSUE THREAD

**Issue by kaktus42** [acdlite/flux-standard-action#31]
Why is `type` defined like

> The type of an action identifies to the consumer the nature of the action that has occurred. Two actions with the same type MUST be strictly equivalent (using ===). By convention, type is usually string constant or a Symbol.

`Two actions with the same type MUST be strictly equivalent`. But if they have different payloads, this is not true anymore.

This doesn't make sense to me.

**Comment by sergej-s** [comment]
Also should action with error=true have different type or can have the same type as result action.

**Comment by JaKXz** [comment]
Thank you for the issue, I think this was addressed in #23.
