### ISSUE TITLE
Should FSA allow Symbol action types?

### ISSUE THREAD

**Issue by yangmillstheory** [acdlite/flux-standard-action#39]
The Redux BDFL has [mentioned before that Symbols as action types is a bad idea](https://github.com/acdlite/redux-actions/issues/20#issuecomment-134340125).

[We're considering dropping support for Symbols in redux-actions](https://github.com/acdlite/redux-actions/issues/126), and wanted to cross-post that issue here since this is really about FSA shape.

Is anyone using Symbols as action types? What are the advantages over using strings? Standardizing on strings would lead to conceptual simplicity and potentially less special-casing.

**Comment by JaKXz** [comment]
@yangmillstheory my thoughts here: https://github.com/acdlite/redux-actions/issues/126#issuecomment-256832993 but I don't have a strong opinion either way so I'm fine with whatever the community decides :)

**Comment by unional** [comment]
Thanks for bringing this up. I would vote for removing Symbol support for simplicity. Keep action serializable. 🌷

**Comment by BerkeleyTrue** [comment]
I'd also vote for removing Symbols since they are not serializable
