### ISSUE TITLE
Typings make meta a required property

### ISSUE THREAD

**Issue by gCardinal** [acdlite/flux-standard-action#59]
Using TypeScript and the included typings makes `meta` a required property in a FSA.

```typescript
import {FluxStandardAction as Action} from 'flux-standard-action'
public static updateYear(year: string): Action<string, null>
{
    return {
        type: Actions.SDS_VEHICLE_SELECTION_YEAR_UPDATE,
        payload: year
    }
}
```

This will complain that `meta` does not exist in my action. Looking at the typings, I see that meta is no longer optional:

```typescript
export interface FluxStandardAction<Payload, Meta> {
  /** ... **/
  meta: Meta;  // Notice the lack of ?
}
```

Is this wanted behavior?

**Comment by JaKXz** [comment]
Please see the discussion in #53. Thanks!

**Comment by JaKXz** [comment]
@gCardinal I'm going to close this for now, hopefully your question is answered. If not, feel free to continue the conversation in #53 to keep the context there.
