### ISSUE TITLE
Meta still not optional

### ISSUE THREAD

**Issue by CharlieHess** [acdlite/flux-standard-action#70]
Even though it was merged in #53, it seems a version has not been published where `meta` is optional. @acdlite can you publish one?

**Comment by JaKXz** [comment]
Hi @CharlieHess sorry for the slow reply, but as you can see #53 was not merged. Please see the discussion there. I'd be open to restarting that discussion if things have changed in the TS community, but it seems to me like the community is ok with the typings the way they are. Let me know if you have any further concerns but I'm going to close this issue to centralize the discussion in #53.

**Comment by KSuttle-cng** [comment]
In the docs, it's still listed as optional.
