### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by goatslacker** [acdlite/flux-standard-action#8]
Continuing from our conversation on slack:

```js
{
  // string | number: a unique identifier for the dispatch
  id: 'abcdef123',

  // any: Symbol, string, number, object, function. A unique way to identify the action dispatched
  type: ActionTypes.ADD_TODO,

  // any: whatever is being dispatched
  payload: { text: 'Create FSA Proposal' },

  // information about the action itself
  action: {
    // string representation of the particular action type
    // since Symbols are not strings and action type can be anything, having a way to identify an
    // action as a string is useful for serializing, debugging, and logging.
    id: 'ActionTypes.ADD_TODO'
  },

  // other information about the dispatch
  meta: {
    // no opinions here...
    status: 'success'
  }
}
```

There's a difference between dispatch and action. I need to uniquely identify dispatches, this is useful for time travel, rollback, etc. I also need to be able to unique identify actions, this is good for logging and debugging.

I think this is a good MVP. I was using `details` for action information in alt but I think action is a better name.

**Comment by acdlite** [comment]
Couldn't you merge `action` and `meta` into a single field?

**Comment by goatslacker** [comment]
Yes you can, I just think `action` is a better name because meta may refer to meta information about the dispatch.

**Comment by acdlite** [comment]
How are you distinguishing between the dispatch and the action? To me they're synonymous. I get your "class vs. instance" analogy from our Slack conversation, but I don't really think it fits. To me the only field here that kinda feels like a "class" property is `type`. And type is meant for introspection. Isn't everything else is specific to the dispatch or "instance"?

**Comment by goatslacker** [comment]
We need more information than just the type. Since the type can be anything. 

In alt I include a string representation of the type, the name of the action, and the namespace.

Everything else is dispatch info.

**Comment by acdlite** [comment]
Okay, so if everything else is dispatch info, `action` and `meta` can be merged together, right?

**Comment by acdlite** [comment]
Could actions in Alt look like this instead?

```js
{
  // any: Symbol, string, number, object, function. A unique way to identify the action dispatched
  type: ActionTypes.ADD_TODO,

  // any: whatever is being dispatched
  payload: { text: 'Create FSA Proposal' },

    // information about the action itself
  meta: {
    // string | number: a unique identifier for the dispatch
    id: 'abcdef123',
    
    // string representation of the particular action type
    // since Symbols are not strings and action type can be anything, having a way to identify an
    // action as a string is useful for serializing, debugging, and logging.
    displayType: 'ActionTypes.ADD_TODO'
  }
}
```

**Comment by goatslacker** [comment]
yeah that looks good enough. Not sure about the displayType name but we can work on it

**Comment by goatslacker** [comment]
Closing this in favor of #4 which looks like a better issue.
