### ISSUE TITLE
Serializable?

### ISSUE THREAD

**Issue by gaearon** [acdlite/flux-standard-action#9]
Should FSA mandate actions to be serializable? I think it's a good requirement (prevents people from passing callbacks inside actions). It's also great for the tooling, as it's easy to build Flux over websockets, or a persistent debug session solution, without worrying that something might get lost.

I propose the following changes:
- `invariant(isDeepEqual(action, JSON.parse(JSON.stringify(action))))`
- Therefore, `type` must be a String, not a Symbol

We could then write a middleware that checks actions for compliance in development.

**Comment by acdlite** [comment]
Yes, I think that's a sensible requirement. However, we should distinguish between "in-flight" actions and "processed" actions that are ready for consumption by a Flux store, reducer, whatever. We should come up with a good term for those, as well.

That way this is still a legal "in-flight" FSA action:

```js
{
  type: 'FETCH_DATA'
  payload: somePromise
}
```

that will be turned into proper "process" FSA actions by middleware or some other library code (trying to stay framework agnostic, remember :smile:):

```js
{
  type: 'FETCH_DATA'
  payload: { id, data, ..stuff }
```

**Comment by acdlite** [comment]
Oh, I forgot that right now the spec says the payload of a failed action should be an error object, which isn't serializable. Not a problem, we can specify that the `payload` of a failed action should (by convention) be

```js
{
  type: 'FETCH_DATA',
  error: true,
  payload: {
    message: "Something's gone wrong",
    fileName: 'index.js',
    lineNumber: 123
  }
}
```

This is a "SHOULD," though, not a "MUST." The only "MUST" is that it is serializable.

**Comment by clearjs** [comment]
@acdlite Defining a point where an action must comply with certain criteria is important. It might depending on criteria.

**Comment by nhunzaker** [comment]
I'm bumping into this writing debug tools as well. Sending actions over `postMessage` is easy enough, but I keep wondering if I should add an assertion for objects that don't conform to:

https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/The_structured_clone_algorithm

The browser will gripe at you if you try to `window.postMessage` an object that doesn't follow this format, but it can be a little alien to get the message out of context.

**Comment by gaearon** [comment]
How about a dev-only middleware that you'd put at the very end, and that warns you when your actions aren't FSA-compliant (or serializable for that matter)?

**Comment by tappleby** [comment]
I think the warn middleware would be handy (in its own repo). Would also be useful to expose a utility method like `isSerializable `

**Comment by ariddell** [comment]
Just hit this.

It seems like serializing the Error object is the tricky part. The convention proposed be @acdlite makes sense to me, e.g.:
```
{
  type: 'FETCH_DATA',
  error: true,
  payload: {
    message: "Something's gone wrong",
    fileName: 'index.js',
    lineNumber: 123
  }
}
```
since this mimics the Error object structure: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

Mentioning this convention in the docs would be welcome.

**Comment by rstuven** [comment]
I implemented an FSA serialization library: https://github.com/rstuven/flux-standard-action-json

I tried to be strict where the FSA spec is (throwing an Error when the action to be serialized/deserialized is not compliant, ie.`!isFSA()`), but flexible enough to support Symbol and Error serialization (thanks to [errio](https://github.com/programble/errio)).

I'll include something like `isSerializable` if FSA settles it down (opt-in or opt-out, depending on how the spec goes).

Hope you find it useful. :)

**Comment by maxmechanic** [comment]
Weirdly I just saw this issue, and have just published something like what @gaearon suggests for linting actions: https://github.com/maxmechanic/redux-fsa-linter

**Comment by jayphelps** [comment]
Are error objects suppose to be only for clientside errors? Cause given your example:
```js
{
  type: 'FETCH_DATA',
  error: true,
  payload: {
    message: "Something's gone wrong",
    fileName: 'index.js',
    lineNumber: 123
  }
}
```

If the error was produced by the server, I'm not sure you have any meaningful fileName and lineNumber. e.g. if `FETCH_DATA`, the server responds with `Unauthorized`
